# Generated by Django 5.1.3 on 2025-01-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_alter_transaction_description_alter_transaction_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
