# Generated by Django 5.1.3 on 2025-01-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_category_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
