# Generated by Django 5.1.3 on 2025-02-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recurring_transactions", "0002_alter_recurringtransaction_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringtransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
