# Generated by Django 5.1.3 on 2025-02-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recurring_transactions", "0003_recurringtransaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringtransaction",
            name="type",
            field=models.CharField(
                choices=[("credit", "Credit"), ("debit", "Debit")], max_length=10
            ),
        ),
    ]
